project:
  type: website

website:
  title: "Abdi Zeraatpisheh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
      - CV.qmd
      - Contact me.qmd
      

format:
  html:
    theme: Academic
    css: styles.css
    toc: true

editor: visual

