project:
  type: website

website:
  title: "Abdi Zeraatpisheh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
      - text: "Assignments"
        menu: 
         - assignment1.qmd
         - Assignment2.qmd
      - CV.qmd
      - Contact me.qmd
      

format:
  html:
    theme: United
    css: styles.css
    toc: true

editor: visual

