---
title: "CV"
---

**ABDOLLAH ZERAATPISHEH**

Ph.D. student in Public Affairs     

Cellphone: (469)961-0355, Skype ID: abdi_z

[Axz180016\@utdallas.edu](mailto:Axz180016@utdallas.edu), [Zeraatpisheh\@gmail.com](mailto:Zeraatpisheh@gmail.com)

[**EDUCATION**]{.underline}

2022 -- The University of Texas at Dallas, TX

Ph.D. candidate in Public Affairs

2009 - Iran University of Science and Technology. Iran

Master's Degree in Executive Management

TA for Mathematics, Statistics, and Microeconomics

2003 - University of Guilan, Iran

Bachelor\'s degree in industrial management

[**RESEARCH INTERESTS**]{.underline}

·        Public HRM

·        Diversity, Inclusion and Equity

·        Job satisfaction and performance

·        Comparative management practices

·        Gender and Leadership

[**WORK EXPERIENCE**]{.underline}

August 2022 - Current

Teaching Assistant

Department of Public and Nonprofit Management, University of Texas at Dallas

<https://epps.utdallas.edu>

September 2020 -- May 2022      

Chief Human Resources Officer

TAPSI (Online Cab Application)

[www.tapsi.ir](http://www.tapsi.ir)

·        Leading long‐range strategic planning to anticipate the innovation of change initiatives that promote people productivity, organizational efficiency, and cost-effectiveness.

·        Maintain an organizational design that is reflective of a dynamic and up-to-date business environment.

·        Leverage management tools to identify, align, and build on the Company's workforce capabilities.

·        Lead the HR department in analyzing and evaluating employee performance, using those analyses to cultivate talent, close gaps, and improve performance.

·        Demonstrate a commitment to equity, excellence, and high expectations for all staff and volunteers by creating organizational policies and structures that remove barriers and foster inclusion for all.

·        Ensure that the organization develops a high-performing, mission-driven culture by strategically gauging staff morale, addressing organizational issues while providing HR solutions, and increasing organizational effectiveness and health; through planned interventions in the organization's processes

·        Participate in strategic planning for the organization. Provide leadership and consulting support to executives and management on reinforcing culture, setting goals, developing policy, and implementing strategic objectives. Align organizational structure, roles, and responsibilities to achieve goals.

·        Oversee talent management, including staff training and leadership development, retention, recognition, employee communication, and career development. Assesses and evaluates training and staff development needs and develops programs to meet requirements.

March 2019 ‐ August 2020          

Chief Human Resources Officer

Snapptrip (Full-service travel booking website)

[www.snapptrip.ir](http://www.snapptrip.ir)

·        Establish and implement HR efforts that effectively communicate and support Snapptrip's mission and strategic vision.

·        Develop HR plans and strategies to support the achievement of the overall business operations objectives.

·        Function as a strategic business advisor to each business unit's executive/senior management regarding key organizational and management issues.

Jan 2018 ‐ March 2019  

Chief Human Resources Officer

bamilo (E-commerce marketplace)

·        Leading long‐range strategic planning to anticipate the innovation of change initiatives that promote people productivity, organizational efficiency, and cost-effectiveness.

·        Ensuring that the business's values are communicated and understood at all company levels, clarifying employee conduct necessary for realizing an engaging, high-performance culture within the Company.

·        Ensuring that the organizational design and rewards structure is reflective of a dynamic business environment and up‐to‐date modes of working in an increasingly competitive business environment.

·        Formulating strategies that lead to quality and depth in the talent employed in the business. Includes leadership, employee development, and securing future business growth focuses on skill and business culture or company culture.

·        Developing comprehensive strategic recruiting and retention plans that meet the business's human capital needs.

·        Playing an analytical role: monitoring, analyzing, and identifying strategic needs, gaps, and risks.

Feb 2017 ‐ Jan 2018

Chief Human Resources Officer

Infotech (IT banking solution provider)

·        Establish and implement HR efforts that effectively communicate and support the Company's mission and strategic vision.

·        Develop HR plans and strategies to support the achievement of the overall business operations objectives.

·        Function as a strategic business adviser to each business unit's executive/senior management regarding key organizational and management issues.

·        Work with the Company's executive management to establish a sound plan of management succession that corresponds to the strategy and objectives of the firm.

·        Develop comprehensive strategic recruiting and retention plans to meet the human capital needs of strategic goals.

·        Develop and implement comprehensive compensation and benefits plans that are competitive and cost-effective for the Company.

·        Provide overall leadership and guidance to the HR function by overseeing talent acquisition, career development, succession planning, retention, training, leadership development, compensation, and benefits globally.

Jul 2014 ‐ Sep 2016         

HR Director

Kayla Group (FMCG distribution)

·        Plan, develop and deploy strategy for HR development within the organization and evaluate HR strategy implementation.

·        Develop and deploy compensation structure, beneficial systems, and incentives to satisfy the needs of employees.

·        Plan, develop and implement the strategy for staff training and development / Play consultancy role to top management team in HR-related fields.

·        Plan departmental/functional budgets (training, recruiting advertisements, consultants, and relevant costs), forecast costs, and monitor the HR budgeting system.

·        Evaluate and monitor the human resources processes (Training process, Performance Appraisals, Hiring, Career Planning, Promotions, and others if relevant)

·        Conduct Job Evaluation Process and Organizational restructuring.

Oct 2005 ‐ May 2011      

Senior Manager HR Operations

MTN Irancell

·        Design, develop and implement cost-effective talent acquisition tools.

·        HR Advisory role to Executive managers regarding legal and employment issues

·        Identify staff vacancies (supply-demand gap) through workforce planning.

·        Ensure that the proper selections of candidates are made according to the approved budget and meet the job requirements of the educational business.

·        Optimize and enhance existing HRIS platform and HR intelligence toolkit.

·        Conducting job fairs, Networking with prestigious universities to attract the best fresh talented student.

·        Manage the recruitment and deployment of expatriate staff from end to end.

·        Develop and align HR operation policies and procedures to MTN group requirements.

·        Perform complex staffing duties, including dealing with under-staffing, refereeing disputes, firing employees, administering disciplinary and H&S procedures, and redundancy.

·        Manage employee benefits and implement the company personnel policy and regulation related to it somewhat but within delegated authority.

·        Co-ordination of talent acquisition and retention through the MTN Group processes

·        Integrating talent care with security issues and medical care, i.e., emergency evacuations/ health care/ movement of staff

·        Maintain employees' relations by attending to their grievances, meeting their requirements and assure overall fairness and motivate for optimum performance.

·        Liaise with Finance for the matters related to budget, final settlement of accounts, and other needs that may arise and necessary for decision making at the Head Office

·        Design and develop an internship program for staff.

·        Enhance the employee value proposition to attract the best talent and become the employer of choice.

·        Develop and manage fair and reliable systems to attract the best talent.

·        Develop a program that will facilitate the realization of the Company's employment equity objectives.

·        Develop strategic alliances with labor brokers, headhunters, recruitment agencies, professional bodies, and education institutions.

Jan 2003 ‐ Jun 2005        

HR Specialist

Iran Khodro (Automaker Company)

[www.ikco.com](http://www.ikco.com)

Jan 2000 ‐ Sep 2003       

HR Specialist

Pars Khazar (Home Appliances manufacturer)

[www.parskhazar.com](http://www.parskhazar.com)
